name: handyman_provider_flutter
description: A new Flutter project.
publish_to: 'none'
version: 11.15.1+103

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.1.8
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.1
  html: ^0.15.6
  http: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_vector_icons: ^2.0.0
  path_provider: ^2.1.5
  dotted_border: ^3.1.0
#  custom_date_range_picker: ^1.1.0

  #Firebase
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_pagination: ^4.2.0
  firebase_messaging: ^16.0.1

  flutter_local_notifications: ^19.4.1
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.4.0
  syncfusion_flutter_charts: ^30.2.7
  geocoding: ^4.0.0
  webview_flutter: ^4.13.0
  country_picker: ^2.0.27

  #image:
  image_picker: ^1.2.0
  photo_view: ^0.15.0
  file_picker: ^10.3.2
  lottie: ^3.3.1
  crop_image: ^1.0.16

  # PAYMENTS
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main  
  phonepe_payment_sdk: ^3.0.1
  flutter_stripe: ^12.0.2
  razorpay_flutter: ^1.4.0
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.5.0
      
  #IN APP PURCHASE
  purchases_flutter: ^9.2.3

  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  custom_map_markers: ^0.0.2+1
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  syncfusion_flutter_pdfviewer: ^30.2.7
  playx_version_update: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  mobx_codegen: ^2.7.2
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/